DROP TABLE IF EXISTS bdd_icono_Image CASCADE;
CREATE TABLE bdd_icono_Image (
id BIGINT PRIMARY KEY NOT NULL,
legende TEXT NULL,
description TEXT NOT NULL,
existe_en_physique BOOLEAN NOT NULL,
cote VARCHAR(150) NULL,
n_cesr VARCHAR(150) NOT NULL,
image_format VARCHAR(10) NOT NULL,
mode VARCHAR(10) NOT NULL,
resolution VARCHAR(50) NOT NULL,
photographie_type VARCHAR(50) NOT NULL,
credit VARCHAR(150) NULL,
permalien VARCHAR(255) NOT NULL,
lien_telechargement VARCHAR(255) NOT NULL,
n_cliche_numerique VARCHAR(150) NULL,
n_cliche_photo VARCHAR(150) NULL,
fk_photographe_id BIGINT NOT NULL,
fk_departement_id BIGINT NOT NULL,
fk_extrait_de_id BIGINT NULL
);

INSERT INTO bdd_icono_Image (id,legende,description,existe_en_physique,cote,n_cesr,image_format,mode,resolution,photographie_type,credit,permalien,lien_telechargement,n_cliche_numerique,n_cliche_photo,fk_photographe_id,fk_departement_id,fk_extrait_de_id) VALUES
('1',null,'En marge du texte des psaumes,un petit lièvre pince entre ses griffes les cordes d’une harpe. L’instrument fait référence à la harpe du roi David,“auteur” des psaumes,mais l’animal s’inscrit en décalage avec la figure dividique et sa musique.',TRUE,'ms. Stowe 17,fol. 92v','im_0389','tiff','Couleur','+ 600 dpi','Numérique',null,'https://www.bl.uk/manuscripts/FullDisplay.aspx?ref=Stowe_MS_17','non-renseigné',null,null,'0','0','37'),
('2',null,'Le jongleur donne du mouvement aux autres personnages des bordures en jouant de la vièle à archet. Sa musique et sa gesticulation répondent au psaume Dixit insipieus (”L’insensé dit que Dieu n’est pas en son coeur” et l’asscient alors au fou blasphémateur qui ne connaît pas Dieu.',TRUE,'ms. Stowe 17,fol. 233v','im_0390','tiff','Couleur','300 dpi','Numérique',null,'https://www.bl.uk/manuscripts/FullDisplay.aspx?ref=Stowe_MS_17','non-renseigné',null,null,'0','0','37'),
('3',null,'non-renseigné',TRUE,'ms. Add. 24686,fol. 17v','im_0391','tiff','Couleur','300 dpi','Numérique',null,'http://www.bl.uk/manuscripts/FullDisplay.aspx?ref=Add_MS_24686','non-renseigné',null,null,'0','0','42'),
('4',null,'Cette image de David organiste se veut à la fois propédeutique et hermétique : il enseigne au jeune joueur de vielle à roue les lois mathématiques de la musique contenues dans les cloches suspendues au-dessus de l’orgue. Son enseignement prépare à la connaissance des choses sacrées : l’inspiration divine de sa musique est figurée non par la colombe de l’Esprit Saint mais par les souffles. David fait ainsi résonner l’harmonie des sphères par les tuyaux de l’orgue d’où s’échappent cinq “bulles” à têtes d’anges',TRUE,'ms. Add. 62935,fol. 97v','im_0392','tiff','Couleur','+ 600 dpi','Numérique',null,'http://www.bl.uk/manuscripts/FullDisplay.aspx?ref=Add_MS_62935','non-renseigné',null,null,'0','0','45'),
('5',null,'La harpe de David comme lien entre la terre et le ciel est ici clairement mis en scène. Dans la partie inférieure de la terre du psaume,cinq représentants des différents ordres religieux jouent d’une sorte de rebec ou de vièle à archet,du dulcimer,de la flûte traversière,du luth et de la flûte. Cet ensemble de bas instruments loue Dieu le Père qui apparaît dans les nuées de la partie supérieure',TRUE,'ms. Add. 15426,fol. 86','im_0393','tiff','Couleur','+ 600 dpi','Numérique',null,'non-renseigné','non-renseigné',null,null,'0','0','43'),
('6',null,'Le roi David,identifiable par son attribut la harpe et l’inscription rex david,est entouré des musiciens qui tiennent un luth,une trompette,un dulcimer,une bombarde,un orgue et une vièle à roue. En tant que Préfigure du Christ,il leur montre les anges qui annoncent en chantant la naissance de l’Enfant,assurant ainsi la transition entre l’Ancien et le Nouveau Testament',TRUE,'ms. Add. 18851,fol. 164','im_0394','tiff','Couleur','300 dpi','Numérique',null,'http://www.bl.uk/manuscripts/FullDisplay.aspx?ref=Add_MS_18851','non-renseigné',null,null,'0','0','4'),
('7',null,'Les musiciens de David entretiennent un lien privilégié et spirituel avec le roi David. Sur les quinze marches qui mènent au temple de Salomon,ils jouent chacun d’un instrument différent. Leur “concert” concrétise le chant des psaumes que David compose à leurs côtés',TRUE,'ms. Add. 18851,fol. 184v','im_0395','tiff','Couleur','+ 600 dpi','Numérique',null,'http://www.bl.uk/manuscripts/FullDisplay.aspx?ref=Add_MS_18851','non-renseigné',null,null,'0','0','4'),
('8',null,'Trois ménestrels à cheval précédent le duc de Bourgogne pour annoncer son retour de chevauchée. En tête des hommes d’armes,les puissantes sonorités des trompettes entourent la personne du prince et signalent sa victoire militaire',TRUE,'ms. Royal 14 D 4,fol. 10','im_0396','tiff','Couleur','+ 600 dpi','Numérique',null,'non-renseigné','non-renseigné',null,null,'0','0','9'),
('9',null,'Lors de sa chevauchée en Artois pendant la guerre de Cent Ans,le duc de Bourgogne fait son entrée dans une ville avec la chevalerie et les fantassins. Deux grandes trompettes “habillées” à ses armes font entendre la puissance militaire et politique du prince et lui ouvrent victorieusement la voie.',TRUE,'ms. Royal 18 E I,fol. 12','im_0397','tiff','Couleur','300 dpi','Numérique',null,'http://www.bl.uk/manuscripts/FullDisplay.aspx?ref=Royal_MS_18_E_I','non-renseigné',null,null,'0','0','29'),
('10',null,'La structure pédagogique de l’image enseigne les lois mathématiques des intervalles et des consonnnces à travers les tailles différentes des cloches,des vases,des cordes et des flûtes. Les “inventeurs” de la musique,Pythagore et le philosophe Philolaos,ainsi que Tubal rapellent la légende de la forge pythagoricienne et délivrent eux-mêmes l’enseignement musical fondé sur le Nombre',TRUE,'ms. Add. 4913,fol. 17','im_0398','tiff','Couleur','+ 600 dpi','Numérique',null,'non-renseigné','non-renseigné',null,null,'0','0','52'),
('11',null,'Alors que le texte relate la quête du Graal par les chevaliers de la table ronde,la marge de cette page tourne en dérision le tournoi,privilège de la noblesse : deux singes soufflent dans une cornemuse et dans une trompette pour accompagner la joute entre un homme et une femme nus,armés d’une quenouille,et chevauchant un bouc et un bélier',TRUE,'ms. 5218,folio 10','im_0399','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b7100017d/f23.item','non-renseigné',null,null,'0','0','13'),
('12',null,'Les ménestrels de cour accueillent solennellement au son des trompettes un cortège princier dans la ville de Tarente. Le joueur de cornemuse dissimulé sous l’estrade ne semble pas contribuer à la sérénade officielle. L’Orient et la mythologie antique servent à la mise en scène de l’aristocratie dans ses rituels sociaux et politiques.',TRUE,'ms. 5087,folio 144v','im_0400','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b550098052/f294.item','non-renseigné',null,null,'0','0','32'),
('13',null,'Dans l’espace clos du jardin,trois ménestrels de cour soufflent dans une trompette et des bombardes. Ils mènent la carole de la noble assemblée sous les yeux du poète et de sa bien-aimée. La musique et la danse insérées dans le verger de la Nature évoquent les rythmes du temps et de la vie.',TRUE,'ms. 19153,folio 7','im_0401','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b60003548/f21.item','non-renseigné',null,null,'0','0','27'),
('14',null,'En marge de l’image de l’autorité royale,les deux figures du fou et de l’homme sauvage concentrent ce que le roi doit et ne doit pas avoir en lui : la folie et la bestialité. La trilogie du roi,du fou et de l’homme sauvage se trouve principalement dans les bordures des Roman d’Alexandre et des chroniques.',TRUE,'ms. Français 56,fol. 74v','im_0402','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b9059132s/f79.item','non-renseigné',null,null,'0','1','18'),
('15',null,'non-renseigné',TRUE,'ms. Français 995,fol. 23','im_0403','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b100212581/f55.item','non-renseigné',null,null,'0','1',null ),
('16',null,'La musique est présente dans la danse macabre soit à travers les squelettes musiciens qui la mènent en rythme,soit sous les traits du Ménestrel. a la suite des autres catégories sociales,il est rallié par le mort qui vante ses charmes et ses talents passés,mais pour lui annoncer sa mort. Revêtu de ses plus beaux atours,le Ménestrel tient une chalemie et dialogue ainsi avec le mort.',TRUE,'ms. Français 995,fol. 24 / Te. 8 Rés. C 21297-301','im_0404','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b100212581/f56.item','non-renseigné',null,null,'0','1','17'),
('17',null,'L’oeuvre de Térence a pour cadre le théâtre antique que l’enlumineur a mis en évidence dans l’espace circulaire du “theatrum”. Sous les traits des histrions et des mimes gréco-romains,il rappelle que les jongleurs assument le rôle d’acteur et de musicien : ils gesticulent,masqués et déguisés,et soufflent dans des trompettes. Le peuple romain écoute la lecture du texte par Calliopus.',TRUE,'ms. 664,fol.1v','im_0405','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b8458135g/f14.item','non-renseigné',null,null,'0','0','51'),
('18',null,'La scène du fou jouant de la musique ou dansant devant le roi a souvent été interprétée comme un “divertissement” à la cour. Or,elle serait plutôt la transposition de l’épisode biblique de David faisant le fou à la cour du roi Achis,qui trouve sont prolongement chez Merlin,Tristan et les fous de cour.',TRUE,'ms. Français 74,fol. 1','im_0406','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b105286103/f43.item','non-renseigné',null,null,'0','1','8'),
('19',null,'Dans une taverne,à l’une des tables,un musicien joue du luth à ses compagnes et à ses compagnons gloutons et ivres à l’excès,débauchés et joyeux. La musique est des tous les plaisirs du corps,auxquels le jongleur est socialement et moralement associé par l’Eglise qui le condamme.',TRUE,'ms. Fr. 6185,fol. 51','im_0407','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b9006774w/f111.item','non-renseigné',null,null,'0','1','39'),
('20',null,'L’enseignement de la musica passe d’abord par l’apprentissage des intervalles et des consonances mathématiques sur les cloches. Les quatre clercs d’université,de tailles et d’âges différents,incarnent alors la connaissance de la théorie musicale et le chant polyphonique inscrits dans le livre noté et transmis à l’élève.',TRUE,'ms. Français 22533,fol. 369v','im_0408','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b90629725/f382.item','non-renseigné',null,null,0,'1','24'),
('21',null,'Le roman de Fauvel,oeuvre satirique est l’unique représentation textuelle et musicale du charivari fait à l’âne Fauvel,bête rousse symbole de tous les vices de la cour de Philippe le Bel. Le charivari est un rite de passage qui a lieu quand un veuf épouse en seconde noces une jeune fille. Les jeunes manifestent leur désaccord par le bruit de toutes sortes d’ustensiles et d’instruments de musique.',TRUE,'ms. Français 146,fol. 34','im_0409','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b8454675g/f83.item','non-renseigné',null,null,0,'1','47'),
('22',null,'Le roman de Fauvel,oeuvre satirique est l’unique représentation textuelle et musicale du charivari fait à l’âne Fauvel,bête rousse symbole de tous les vices de la cour de Philippe le Bel. Le charivari est un rite de passage qui a lieu quand un veuf épouse en seconde noces une jeune fille. Les jeunes manifestent leur désaccord par le bruit de toutes sortes d’ustensiles et d’instruments de musique.',TRUE,'ms. Français 146,fol. 36v','im_0410','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b8454675g/f88.item','non-renseigné',null,null,0,'1','47'),
('23',null,'Martin le Franc prend la défense des femmes contre les attaques des clercs misogynes. Dédiant son oeuvre la champion des Dames au duc Philippe le Bon,il célèbre le raffinement intellectuel de sa cour,entretenu notamment grâce aux deux compositeurs de l’époque,Guillaume Dufay et Gilles Binchois. Leur savoir théorique de la musique est symbolisé par leurs instruments,la harpe et l’orgue,dont ils ne jouent pas.',TRUE,'ms. Fr. 12476,fol. 98','im_0411','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b525033083/f201.item','non-renseigné',null,null,0,'1','22'),
('24',null,'En vue d’instruire le duc de Bourgogne,Martin le Franc évoque l’un des “inventeurs” biblique de la musique,Tubalcaïn,également ancêtre des forgerons. Dans cette miniature,il frappe sur un jeu de sept cloches avec deux marteaux,tandis que deux chantres transposent,par la voix,la musique notée dans le livre,sous l’autorité de dame Musica. La musique est présentée comme une discipline scientifique et un moyen de connaissance.',TRUE,'ms. Français 12476,folio 97v','im_0412','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b525033083/f200.item','non-renseigné',null,null,0,'1','22'),
('25',null,'Comme le texte de Matin le Franc l’indique,chacune des neuf muses joue d’un instrument de bas - flûte à bec,harpe,orgue portatif,luth,mandore -,seule l’une d’elles souffle dans une trompette. L’image et le texte établissent ainsi les rapports étroits entre les origines mythologiques de la musique et la poésie,entre la mélodie,la rythmique et la métrique.',TRUE,'ms. Français 12476,fol. 109','im_0413','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b525033083/f224.item','non-renseigné',null,null,0,'1','22'),
('26',null,'Sous le regard des princes et des dames qui remettront le prix au vainqueur,les chevaliers s’apprêtent à tournoyer au son des trompettes. Les couleurs vives et les traits élancés des bannières et des trompettes assurent un mouvement dynamique dans toute la double page de ce manuel didactique flamand,dont le modèle a été crée dans l’entourage du roi René en Provence.',TRUE,'ms. Français 2693,fol. 60v et 61','im_0414','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b8449033b/f142.item','non-renseigné',null,null,0,'1','25'),
('27',null,'Sous le regard des princes et des dames qui remettront le prix au vainqueur,les chevaliers s’apprêtent à tournoyer au son des trompettes. Les couleurs vives et les traits élancés des bannières et des trompettes assurent un mouvement dynamique dans toute la double page de ce manuel didactique flamand,dont le modèle a été crée dans l’entourage du roi René en Provence.',TRUE,'ms. Français 2693,fol. 60v et 61','im_0415','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b8449033b/f142.item','non-renseigné',null,null,0,'1','25'),
('28',null,'La cornemuse qui fait danser la farandole de la bordure marginale est le pendant profane et festif de l’Annonce aux bergers faite par la voix de l’ange dans la miniature. Musique vocale et religieuse et musique instrumentale se répondent et se complètent pour célébrer la nouvelle de la naissance de l’Enfant.',TRUE,'ms. Nv. Acq. lat. 3145,fol. 53','im_0416','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b10025448r/f113.item','non-renseigné',null,null,0,'1','34'),
('29',null,'Selon l’Apocalypse 8,2 de Jean,les sept anges sonnent l’ouverture du septième sceau. Ils tiennent leur instrument en direction du bas,prêts à jouer devant l’autel où Dieu apparaît dans une mandorle. Le bruit des trompettes angéliques rythme les événements successifs de la Révélation de l’évangéliste,car ils sont la voix de Dieu qui annonce la fin des temps.',TRUE,'ms. Néerl. 3,fol. 16','im_0417','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b10532634z/f39.item','non-renseigné',null,null,0,'1','1'),
('30',null,'Le petit chien soufflant dans une trompe devant un lièvre debout sur ses deux pattes évoque la chasse qui,sans chasseur,tourne à la scène de dressage animal le lièvre nargue le chien qui le dresse avec une mélodie qui n’est pas celle des psaumes.',TRUE,'ms. Latin 10435,fol. 149','im_0418','tiff','Couleur','+ 600 dpi','Numérique',null,'https://images.bnf.fr/detail/913455','non-renseigné',null,null,0,'1','44'),
('31',null,'Une multitude d’anges joue de tous les instruments de musique et symbolise le monde céleste et divin que le frère dominicain doit prendre comme modèle sur terre pour instruire le duc Jean de Berry. Le concert angélique est une représentation chrétienne de l’antique “harmonie des sphères”,expression parfaite de l’ordre cosmique.',TRUE,'ms. Latin 18014,fol. 8','im_0419','tiff','Couleur','+ 600 dpi','Numérique',null,'https://images.bnf.fr/detail/725929','non-renseigné',null,null,0,'1','40'),
('32',null,'Le couronnement de la Vierge est célébré par les anges qui l’entourent de la musique de leurs instruments. Disposés en rond,ils incarnent l’antique musique des sphères et la perfection du cosmos crée par Dieu.',TRUE,'ms. Latin 18014,fol. 48v','im_0420','tiff','Couleur','+ 600 dpi','Numérique',null,'https://images.bnf.fr/detail/879397','non-renseigné',null,null,0,'1','41'),
('33',null,'La miniature distingue la musiqe des anges de celle des bergers. Dans le ciel bleu,les anges annoncent par leur chant la naissance du Christ aux bergers. Parmi ces derniers,l’un d’eux joue de la cornemuse,alors que son compagnon interrompt sa musique pour entendre ma nouvelle. La musique vocale évoque le monde divin et céleste,tandis que la pratique instrumentale désigne la société des hommes.',TRUE,'ms. Latin 18014,fol. 40v','im_0421','tiff','Couleur','+ 600 dpi','Numérique',null,'https://images.bnf.fr/detail/652467','non-renseigné',null,null,0,'1','40'),
('34',null,'Le couronnement de la Vierge est célébré par les anges qui l’entourent de la musique de leurs instruments. Disposés en rond,ils incarnent l’antique musique des sphères et la perfection du cosmos crée par Dieu.',TRUE,'ms. Latin 18014,fol. 48v','im_0422','tiff','Couleur','+ 600 dpi','Numérique',null,'https://images.bnf.fr/detail/879397','non-renseigné',null,null,0,'1','41'),
('35',null,'La colère de Saül est extériorisée par le grotesque flûtiste et celui qui souffle dans une cornemuse de part et d’autre de la miniature. Figures du démon et de la folie,ils représentent à la fois l’humeur colérique (la maladie) et le remède de la folie du roi : en marge de l’image,leur musique est une imitation décalée de la harpe de David et une référence aux effets bénéfiques de la musique sur les troubles de l’esprit.',TRUE,'ms. Latin 10483,fol. 24v','im_0423','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b8451634m/f50.item','non-renseigné',null,null,0,'1','5'),
('36',null,'Le psaume est bordé d’un curieux grotesque musicien,familier de l’iconographie marginale de l’enlumineur parisien Jean Pucelle. A l’extrémité droite de la marge inférieure,chevauchant un monstre,il souffle dans un soufflet à feu,de l’Enfer et du silence. Plus haut,deux autres hybrides dialoguent corps à corps.',TRUE,'ms. Latin 10483,fol. 37v','im_0424','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b8451634m/f75.item','non-renseigné',null,null,0,'1','5'),
('37',null,'La vièle à archet est au coeur du miracle qui se réalise par le son et l’image devant le clergé et les pèlerins de Rocamadour. L’instrument souligne le mouvement de conversion du pécheur sous l’effet de la musique et de l’apparition mariale. Il tisse le lien entre le jongleur et l’au-delà.',TRUE,'ms. 22938,fol. 222v','im_0425','tiff','Couleur','+ 600 dpi','Numérique',null,'non-renseigné','non-renseigné',null,null,0,'1','35'),
('38',null,'Dans le registre supérieur,Dame Fortune,les yeux bandés,fait tourner la roue du temps et du destin des hommes entourée de deux ménestrels. Le registre inférieur en montre les effets dans le cadre d’une cour aristocratique ; les nobles danseurs donnent du mouvement à la danse en couples en levant les pieds et en se donnant la main.',TRUE,'ms. Français 1696,fol. 11v','im_0426','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b9059041d/f13.item','non-renseigné',null,null,0,'1','16'),
('39',null,'La danse fait partie des “esbatements” de la société de cour. Elle est souvent rythmée au son du tambourin et de la flûte joués par le menestrel. Elle a également pour vertu morale et didactique d’enseigner aux jeunes nobles à maitriser leur corps,à bien se tenir et à discipliner leurs moeurs.',TRUE,'ms. Français 288,fol. 181v','im_0427','tiff','Couleur','+ 600 dpi','Numérique',null,'https://images.bnf.fr/detail/926777','non-renseigné',null,null,0,'1','36'),
('40',null,'Le banquet relève de la vie diplomatique. Alexandre le Grand réunit les chevaliers et les conseillers,débat avec eux et son fils des affaires du royaume et reçoit un message. Les ménestrels soufflent dans une bombarde et des trompettes pour annoncer le service des plats. Ils confèrent une dimension solennelle à cet événement politique.',TRUE,'ms. Français 9342,fol. 13','im_0428','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b6000083z/f35.item','non-renseigné',null,null,0,'1','20'),
('41',null,'Les portes de Paris souvent au son des trompettes du duc de Bourgogne. Ses ménestrels annoncent l’entrée solennelle du roi de France entouré de la noblesse. Par leur puissance sonore,les instruments symbolisent la voix du prince qu’ils servent et représentent.',TRUE,'ms. Français 2679,fol. 322','im_0429','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b10544597d/f648.item','non-renseigné',null,null,0,'1','28'),
('42',null,'Les portes de Paris s’ouvrent au son des trompettes du duc de Bourgogne. Ses ménestrels annoncent l’entrée solennelle du roi de France entouré de la noblesse. Par leur puissance sonore,les instruments symbolisent la voix du prince qu’ils servent et représentent.',TRUE,'ms. Français 2679,fol. 413','im_0430','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b10544597d/f829.item','non-renseigné',null,null,0,'1','28'),
('43',null,'Sous les traits d’un roi du XVe siècle,l’empereur Alexandre le Grand fait son entrée solennelle dans une ville aux rues jonchées de fleurs et aux murs et fenêtres ornées de vaisselles et de tapisseries précieuses. Une multitude de joueurs',TRUE,'ms. Français 22547,fol. 254v','im_0431','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b8449039t/f520.item','non-renseigné',null,null,0,'1','46'),
('44',null,'Au cours du banquet et conduis par le Grand Echanson,les ménestrels annoncent à coup de trompettes et de bombardes le début du repas et le service des plats. Loin de divertir les convives,les trompettistes font partie du cérémonial de cour et des rituels de la table,rigoureusement réglés à la cour de Bourgogne.',TRUE,'ms. Français 12574,folio 181v','im_0432','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b8449031h/f368.item','non-renseigné',null,null,0,'1','11'),
('45',null,'Une joyeuse farandole d’animaux vient curieusement border le prologue de la bible latine offerte par le banquier Rapondi au duc Philippe le Hardi. La diversité instrumentale alliée au rythme des couleurs et des danseurs est guidée par l’idée d’ordre et d’harmonie propre à la danse et à la musique.',TRUE,'ms. 9157,fol. 1','im_0433','tiff','Couleur','600 dpi','Numérique',null,'https://uurl.kbr.be/1787409','non-renseigné',null,null,'0','0','3'),
('46',null,'Les sonorités criardes de la cornemuse contribuent aux tourments des damnés dans la fournaise de l’Enfer. Ce magnifique manuscrit de la Cité de Dieu de saint Augustin,le traité théologico-politique qui fait autorité durant tout le moyen Age,a été enluminé par le Maître de Guillebert de Mets sur la commande de Guy de Guilbaut,conseiller du duc Philippe le Bon et premier maître de la chambre des comptes à Lille.',TRUE,'ms. 9006,fol. 265v','im_0434','tiff','Couleur','600 dpi','Numérique',null,'https://portail.biblissima.fr/ark:/43093/mdata5c4c59d5ac0ab16dc0f121c4974c6c00460bd045','non-renseigné',null,null,'0','0',null ),
('47',null,'Chaque étape de l’ascension de la Vierge est rythmée par les instruments des anges. La musique et les anges remplissent une fonction psychopompe,ils guident les âmes dans leur voyage céleste.',TRUE,'ms. 9006,fol. 293v','im_0435','tiff','Couleur','600 dpi','Numérique',null,'https://portail.biblissima.fr/ark:/43093/mdata5c4c59d5ac0ab16dc0f121c4974c6c00460bd045','non-renseigné',null,null,'0','0','14'),
('48',null,'La Visitation de l’ange Gabriel à la Vierge est annoncée par la musique de trois anges qui jouent du luth,du psaltérion et qui chantent. Le duc de Bourgogne assiste en prière à l’évènement. Commanditaire de cette oeuvre morale. Philippe le Bon s’est fait représenter en prince chrétien et dévot qu’il est.',TRUE,'ms. 9270,fol. 2v','im_0436','tiff','Couleur','600 dpi','Numérique',null,'https://portail.biblissima.fr/fr/ark:/43093/mdataf41fa127d0a2b6096d26a121206bed705276207e','non-renseigné',null,null,'0','0','53'),
('49',null,'En introduction,au premier des 150 psaumes,le Beatus vir,le roi David couronné et assis sur un trône,joue de la harpe,son instrument - attribut. Il est donné par un jeu de cloches qui rappelle l’essence mathématique et savante de sa musique. Le comte de Flandre et son épouse,propriétaires du bréviaire,figurent dans la marge inférieur.',TRUE,'ms. 9427,fol. 17','im_0437','tiff','Couleur','600 dpi','Numérique',null,'https://uurl.kbr.be/1756146','non-renseigné',null,null,'0','0','6'),
('50',null,'non-renseigné',TRUE,null,'im_0438','tiff','Couleur','600 dpi','Numérique',null,'non-renseigné','non-renseigné',null,null,'0','0',null ),
('51',null,'L’arbre de Jessé représente la généalogie de la Vierge et du Christ entourés des rois de Juda qui jouent tous d’un instrument de musique. Propriétaire de ce livre de prières,le duc Philippe le Bon s’inscrit dans la descendance spirituelle et christique.',TRUE,'ms. 9511,fol. 15','im_0439','tiff','Couleur','600 dpi','Numérique',null,'https://uurl.kbr.be/1627210','non-renseigné',null,null,'0','0','7'),
('52',null,'Du haut d’une tribune,un officier du prince lit devant les élites de la ville une ordonnance à laquelle un sceau est suspendu. Il est accompagné d’un ménestrel qui sonne l’annonce publique au son de la trompette,porte-parole officiel des autorités urbaines et princières.',TRUE,'ms. 7,fol. 18v','im_0440','tiff','Couleur','600 dpi','Numérique',null,'https://uurl.kbr.be/1757470','non-renseigné',null,null,'0','0','12'),
('53',null,'Les trois ménestrels de cour sonnent du haut de leur tribune le service des mets du banquet à la cour. Ils souffrent dans une sacqueboute et deux bombardes aux ordres du grand échanson. Au centre de la salle,il règle le rituel des plats et des boissons que le domestiques s’empressent de servir.',TRUE,'ms. 8,fol. 33v','im_0441','tiff','Couleur','+ 600 dpi','Numérique',null,'https://uurl.kbr.be/1751418','non-renseigné',null,null,'0','0','12'),
('54',null,'Les trompettistes à cheval participent à la structure géométrique d’ensemble de l’image : les instruments font écho aux lances,aux épées et aux arcs des hommes d’armes ; ils désignent par leurs sonorités puissantes et leurs tubes élancés les deux armées en marche l’un contre l’autre.',TRUE,'ms. 9066,fol. 294','im_0442','tiff','Couleur','600 dpi','Numérique',null,'https://uurl.kbr.be/1878280','non-renseigné',null,null,'0','0','30'),
('55',null,'Les conseillers enseignent au roi les verrues de la sagesse et de la modération par le chant et la harpe,référence au roi David. Par ses fondements mathématiques et sacrés,la musique symbolise l’ordre et la paix sociale que le roi doit établir en son royaume.',TRUE,'ms. 9474,fol. 41v','im_0443','tiff','Couleur','600 dpi','Numérique',null,'https://uurl.kbr.be/1730615','non-renseigné',null,null,'0','0','10'),
('56',null,'De bas en haut,l’image de ce traité mystique et moral indique le parcours pédagogique et intellectuel des études. Les fondements sont les sept arts libéraux situés en bas de part et d’autre de la voûte céleste : sept allégories féminines du trivium et du quadrivium portent les attributs de leur discipline. Musica à droite pince les cordes du psaltérion et dispose d’un petit orgue. Le but ultime de leur étude est la science théologique représentée en haut par “l’Ecole de théologie dont le maistre est sapience,la doctrine vérité et la fin aloué pardonnable” comme l’indique l’inscription supérieure.',TRUE,'ms. IV 111,fol. 90v','im_0444','tiff','Couleur','+ 600 dpi','Numérique',null,'https://portail.biblissima.fr/ark:/43093/mdata422ea839080a7159ecd0d140b0fddda35ab821c5','non-renseigné',null,null,'0','0','54'),
('57',null,'non-renseigné',TRUE,null,'im_0445','tiff','Couleur','+ 600 dpi','Numérique',null,'non-renseigné','non-renseigné',null,null,'0','0',null ),
('58',null,'Ce Roman d’Alexandre enluminé en Flandre pour le roi d’Angleterre relate les hauts faits d’Alexandre le Grand. La dimension orale du récit semble mise en image et en musique par les jongleurs et les acrobates des nombreuses marges enluminées du livre. Dans celle-ci,deux d’entre eux jouent des cloches,du tambourin et de la flûte,un autre déguisé en animal dresse un chien,un dernier danse avec un ours,un singe est arraché et un grand cerf souffle dans une trompette.',TRUE,'ms. Douce 264,fol. 117v','im_0446','tiff','Couleur','+ 600 dpi','Numérique',null,'https://digital.bodleian.ox.ac.uk/objects/4eb290ef-8a15-41b5-9046-ce355dede25e/','non-renseigné',null,null,'0','0','26'),
('59',null,'Ce Roman d’Alexandre enluminé en Flandre pour le roi d’Angleterre relate les hauts faits d’Alexandre le Grand. La dimension orale du récit semble mise en image et en musique par les jongleurs et les acrobates des nombreuses marges enluminées du livre. Dans celle-ci,deux d’entre eux jouent des cloches,du tambourin et de la flûte,un autre déguisé en animal dresse un chien,un dernier danse avec un ours,un singe est arraché et un grand cerf souffle dans une trompette.',TRUE,'ms. Douce 264,fol. 117v','im_0447','tiff','Couleur','+ 600 dpi','Numérique',null,'https://digital.bodleian.ox.ac.uk/objects/4eb290ef-8a15-41b5-9046-ce355dede25e/','non-renseigné',null,null,'0','0','26'),
('60',null,'Par sa musique et son corps animal,la sirène incarne le vice et la luxure. Sur le modèle des marins d’Ulysse,le bestiaire médiéval engage à ne pas se laisser bercer par son chant et ses mélodies instrumentales,dont le pouvoir de séduction amoureuse peut être fatal.',TRUE,'ms. 526,fol. 23v','im_0448','tiff','Couleur','+ 600 dpi','Numérique',null,'http://patrimoine.bm-dijon.fr/pleade/img-viewer/MS00526/viewer.html','non-renseigné',null,null,'0','0','21'),
('61',null,'La danse à la cour est menée au son du tambourin et de la flûte. Par sa position centrale,le ménestrel structure l’image et rythme la farandole. Le roman chevaleresque du Graal contribue à transmettre les valeurs courtoises que l’aristocratie immortalise notamment par l’art de l’enluminure et les rituels mondains tels que la danse.',TRUE,'ms. 526,fol. 1','im_0449','tiff','Couleur','600 dpi','Numérique',null,'http://patrimoine.bm-dijon.fr/pleade/img-viewer/MS00526/viewer.html','non-renseigné',null,null,'0','0','23'),
('62',null,'Sur les murailles de la cité terrestre et pécheresse,le joueur de tambourin et de flûte fait danser une farandole de diablotins et répond à son alter ego diabolique qui joue des mêmes instruments en Enfer. Dans cette oeuvre théologico-morale de référence au Moyen Age,la Cité de Dieu domine la société des hommes à qui elle doit servir de modèle.',TRUE,'ms. 1,fol. 7','im_0450','tiff','Couleur','+ 600 dpi','Numérique',null,'https://arca.irht.cnrs.fr/ark:/63955/md096683053z','non-renseigné',null,null,'0','0','15'),
('63',null,'Musique et couleurs folles trouvent curieusement leur place dans la Bible de Nicolas Rolin,le puissant chancelier du duc de Bourgogne,Philippe le Bon. En marge du texte des Proverbes de Salomon sur la Sagesse,la folie circule à travers le souffle de la cornemuse jouée par un homme sauvage,et le soufflet que porte,à la place de la mitre épiscopale,un petit évêque des fous en habit bicolore à grelots.',TRUE,'ms. 275,fol. 3v','im_0451','tiff','Couleur','+ 600 dpi','Numérique',null,'https://arca.irht.cnrs.fr/ark:/63955/md708w32tt0g','non-renseigné',null,null,'0','0','2'),
('64',null,'Musique et couleurs folles trouvent curieusement leur place dans la Bible de Nicolas Rolin,le puissant chancelier du duc de Bourgogne,Philippe le Bon. En marge du texte des Proverbes de Salomon sur la Sagesse,la folie circule à travers le souffle de la cornemuse jouée par un homme sauvage,et le soufflet que porte,à la place de la mitre épiscopale,un petit évêque des fous en habit bicolore à grelots.',TRUE,'ms. 275,fol. 3v','im_0452','tiff','Couleur','+ 600 dpi','Numérique',null,'https://arca.irht.cnrs.fr/ark:/63955/md708w32tt0g','non-renseigné',null,null,'0','0','2'),
('65',null,'Un chapitre de ce traité de bonne santé est consacré à la musique “Organare cantare vel sonareé” dans le but de soigner la mélancolie rétablit l’harmonie entre les tempéraments,le corps et l’âme. Dans un cadre aristocratique,trois ménestrels de cour chantent et jouent ensemble de la vièle à archet et de l’orgue.',TRUE,'Ms. Ser. Nv. 2644,fol. 103v','im_0453','tiff','Couleur','+ 600 dpi','Numérique',null,'http://data.onb.ac.at/rep/10020524','non-renseigné',null,null,'0','0','50'),
('66',null,'La tête appuyée sur la main,signe de sa mélancolie,Tristan trouve du réconfort à sa douleur en écoutant les mélodies de la harpe d’Iseut. Le cadre architectural et naturel de la scène évoque le jardin de l’amour dans lequel les amants accordent leurs coeurs et leurs corps en musique',TRUE,'ms. 2537,fol. 103','im_0454','tiff','Couleur','+ 600 dpi','Numérique',null,'https://digital.onb.ac.at/rep/osd/?10DFDE53','non-renseigné',null,null,'0','0','48'),
('67',null,'non-renseigné',TRUE,'ms. 1857,fol. 151','im_0455','tiff','Couleur','+ 600 dpi','Numérique',null,'http://data.onb.ac.at/dtl/7456416','non-renseigné',null,null,'0','0','38'),
('68',null,'La salle d’étuves,que l’auteur présente à l’empereur,associe les plaisirs des corps aux cinq sens. Au centre,le joueur de luth réjouit l’ouïe des couples nus qui se baignent et s’embrassent en dégustant des mets et des boissons. La musique ajoute à la volupté des gestes et des moeurs des Romains,condamnés dans cette chronique historique et morale de l’Antiquité romaine tardive',TRUE,'ms. Redh. 2,fol. 244','im_0456','tiff','Couleur','+ 600 dpi','Numérique',null,'non-renseigné','non-renseigné',null,null,'0','0','31'),
('69',null,'Sur la place d’une ville flamande,un condamné est fouetté publiquement sous les insultes des habitants. Devant le Christ en croix,le trompettiste incarne l’ordre politique et moral,il est la voix de la justice qui terrorise et qui condamne.',TRUE,'ms. Redh. 3,fol. 44','im_0457','tiff','Couleur','+ 600 dpi','Numérique',null,'non-renseigné','non-renseigné',null,null,'0','0','33'),
('70',null,'Le singe,par sa similitude avec l’homme,fait partie de l’inventaire des encyclopédie de toutes les créatures du monde. Il se moque dans cette bordure marginale des instrncts corporels et animaux de l’homme : il joue de la vièle avec un soufllet à feu au lieu d’utiliser un véritable instrument mélodieux,il urine habilement dans un flacon et il lâche un pet. L’être humain crée “à l’image de Dieu” est ici tourné en dérision et renvoyé à sa part bestiale.',TRUE,'ms. 61 E,fol. 1','im_0458','tiff','Couleur','300 dpi','Numérique',null,'https://hdl.handle.net/2268.1/8262','non-renseigné',null,null,'0','0','49'),
('71',null,'Les ménestrels de cour,richement vêtus,sonnent de leurs trompettes,le service des plats. a la cour de bourgogne,le banquet repose sur une sorte de liturgie ritualisée dont la mise en scène sollicite aussi bien la vue que l’ouïe,l’odorat ou le goût. La musique fait partie du cérémonial de cour qui sert à impressionner les convives et donc à renforcer l’autorité ducale.',TRUE,'ms. Français 12201,fol. 10v','im_0459','tiff','Couleur','+ 600 dpi','Numérique',null,'https://gallica.bnf.fr/ark:/12148/btv1b8452199j/f30.item','non-renseigné',null,null,'0','0','19');


DROP SEQUENCE IF EXISTS bdd_icono_Image_id_seq;
CREATE SEQUENCE bdd_icono_Image_id_seq START WITH 71;


DROP TABLE IF EXISTS bdd_icono_DepartementCollection CASCADE;
CREATE TABLE bdd_icono_DepartementCollection (
id BIGINT PRIMARY KEY NOT NULL,
departement_nom VARCHAR(255) NOT NULL,
fk_institution_id BIGINT NULL
);

INSERT INTO bdd_icono_DepartementCollection (id,departement_nom,fk_institution_id) VALUES 
('1','Départements des Manuscrits, Division Occidentale','1');


DROP SEQUENCE IF EXISTS bdd_icono_DepartementCollection_id_seq;
CREATE SEQUENCE bdd_icono_DepartementCollection_id_seq START WITH 1;


DROP TABLE IF EXISTS bdd_icono_ExtraitDe CASCADE;
CREATE TABLE bdd_icono_ExtraitDe (
id BIGINT PRIMARY KEY NOT NULL,
extrait_de_nom VARCHAR(255) NOT NULL,
categorie VARCHAR(255) NOT NULL,
date_creation VARCHAR(255) NULL,
periode_creation VARCHAR(255) NULL
);

INSERT INTO bdd_icono_ExtraitDe (id,extrait_de_nom,categorie,date_creation,periode_creation) VALUES 
('1','Apocalypse flamande','Manuscrits',null,'15e siècle'),
('2','Bible de Nicolas Rolin','Manuscrits','vers 1460','15e siècle'),
('3','Bible latine de Philippe le Hardi','Manuscrits','1310-1320','14e siècle'),
('4','Bréviaire d’Isabelle d’Espagne','Manuscrits','vers 1497','15e siècle'),
('5','Bréviaire de Belleville','Manuscrits','vers 1330-1355','14e siècle'),
('6','Bréviaire de Louis de Maele','Manuscrits','vers 1325','14e siècle'),
('7','Bréviaire de Philippe le Bon','Manuscrits','vers 1455','15e siècle'),
('8','Chroniques d’Angleterre de Jean de Wavrin','Manuscrits',null,'15e siècle'),
('9','Chroniques de Froissart','Manuscrits',null,'15e siècle'),
('10','De regimine principum de Gilles de Rome','Manuscrits','vers 1435-1440','15e siècle'),
('11','Histoire d’Olivier de Castille et Artus d’Algarbe','Manuscrits','après 1467','15e siècle'),
('12','Histoire de Charles Martel','Manuscrits','vers 1463-1465','15e siècle'),
('13','Histoire de Saint Graal de Gautier','Manuscrits','1351','14e siècle'),
('14','La Cité de Dieu de saint Augustin','Manuscrits',null,'15e siècle'),
('15','La Cité des Dieux de saint Augustin','Manuscrits','vers 1450','15e siècle'),
('16','La Danse aux aveugles de Pierre Michaut','Manuscrits',null,'15e siècle'),
('17','La danse macabre d’Antoine Vérard : Estampes','Manuscrits','1490','15e siècle'),
('18','La fleur des Histoires de Quinte-Curce','Manuscrits',null,'15e siècle'),
('19','La Fleur des Hystoires de la Terre d’Orient de Jean Mansel','Manuscrits','vers 1402-1403','15e siècle'),
('20','La Geste d’Alexandre le Grand','Manuscrits','1448','15e siècle'),
('21','Le Bestiaire d’amour rimé de Richard de Fournival','Manuscrits',null,'14e siècle'),
('22','Le Champion des Dames de Martin le Franc','Manuscrits','1442','15e siècle'),
('23','Le conte de la Queste du Graal','Manuscrits',null,'15e siècle'),
('24','Le Livre des propriétés des choses de Barthélémy l’Anglais','Manuscrits',null,'15e siècle'),
('25','Le livre des Tournois de René d’Anjou','Manuscrits','1480','15e siècle'),
('26','Le Roman d’Alexandre','Manuscrits','vers 1338-1344','14e siècle'),
('27','Le Roman de la Rose','Manuscrits',null,'15e siècle'),
('28','Les chroniques d’Enguerran de Monstrelet','Manuscrits',null,'15e siècle'),
('29','Les Chroniques de Froissart','Manuscrits',null,'15e siècle'),
('30','Les Chroniques et conquêtes de Charlemagne','Manuscrits',null,'15e siècle'),
('31','Les dits des Romains de Valère-Maxime','Manuscrits','1470','15e siècle'),
('32','Les fleurs des Hystoires de la Terre d’Orient de Jean Mansel','Manuscrits','avant 1467','15e siècle'),
('33','Les Grandes Chroniques de Jean Froissart','Manuscrits',null,'14e siècle'),
('34','Les Heures de Jeanne de Navarre','Manuscrits',null,'14e siècle'),
('35','Les miracles de la Vierge de Gautier de Coincy','Manuscrits','vers 1430','15e siècle'),
('36','Les moeurs des Romains de Valère Maxime','Manuscrits','1469','15e siècle'),
('37','Livre d’heure à l’usage de Maastricht','Manuscrits','vers 1340','14e siècle'),
('38','Livre de prières de Charles le Téméraire, enluminé par Philippe de Mazerolles','Manuscrits',null,'15e siècle'),
('39','Moeurs des Romains de Valère-Maxime','Manuscrits',null,'15e siècle'),
('40','Petites Heures du duc de Berry','Manuscrits',null,'14e siècle'),
('41','Petites Heures du duc Jean de Berry','Manuscrits',null,'14e siècle'),
('42','Psautier Alfonson','Manuscrits',null,'14e siècle'),
('43','Psautier flamand','Manuscrits',null,'15e siècle'),
('44','Psautier picard','Manuscrits',null,'14e siècle'),
('45','Psautier Rutland','Manuscrits',null,'13e siècle'),
('46','Roman d’Alexandre','Manuscrits','1463','15e siècle'),
('47','Roman de Fauvel de Gervais de Bus et Raoul Chaillou de Pestain','Manuscrits','vers 1320','14e siècle'),
('48','Roman de Tristan et de la demoiselle','Manuscrits',null,'15e siècle'),
('49','Speculum historiale de Vincent de Beauvais','Manuscrits',null,'14e siècle'),
('50','Tacuinum sanitatis','Manuscrits',null,'15e siècle'),
('51','Térence des ducs','non-renseigné',null,null ),
('52','Theorica musica de Franchinus Gafurius','Manuscrits',null,'15e siècle'),
('53','Traité sur la Salutation angélique','Manuscrits','1461','15e siècle'),
('54','Traités mystiques et sermons de Jean Gerson','Manuscrits',null,'15e siècle');


DROP SEQUENCE IF EXISTS bdd_icono_ExtraitDe_id_seq;
CREATE SEQUENCE bdd_icono_ExtraitDe_id_seq START WITH 54;


DROP TABLE IF EXISTS bdd_icono_Theme CASCADE;
CREATE TABLE bdd_icono_Theme (
id BIGINT PRIMARY KEY NOT NULL,
theme_libelle VARCHAR(255) NOT NULL
);

INSERT INTO bdd_icono_Theme (id,theme_libelle) VALUES 
('1','Etre humain'),
('2','Concept et abstraction'),
('3','Evénement et portrait historique'),
('4','Mythologie classique et histoire ancienne'),
('5','Nature'),
('6','Nature morte'),
('7','Nature, animal'),
('8','Nature, mammifère'),
('9','Nature, paysage'),
('10','Nature, plante'),
('11','Religion chrétienne'),
('12','Religion chrétienne, Nouveau Testament'),
('13','Religion judéo-chrétienne, Ancien Testament'),
('14','Société, civilisation et culture'),
('15','Société, civilisation et culture, affaire militaire'),
('16','Société, civilisation et culture, art'),
('17','Société, civilisation et culture, art, architecture'),
('18','Société, civilisation et culture, art, art de la scène'),
('19','Société, civilisation et culture, art, danse'),
('20','Société, civilisation et culture, art, festivités'),
('21','Société, civilisation et culture, art, industrie manuelle'),
('22','Société, civilisation et culture, art, littérature'),
('23','Société, civilisation et culture, art, musique'),
('24','Société, civilisation et culture, art, ornement'),
('25','Société, civilisation et culture, art, sculpture'),
('26','Société, civilisation et culture, demeure'),
('27','Société, civilisation et culture, écriture'),
('28','Société, civilisation et culture, Etat, loi, vie politique'),
('29','Société, civilisation et culture, famille'),
('30','Société, civilisation et culture, festivités'),
('31','Société, civilisation et culture, industrie manuelle'),
('32','Société, civilisation et culture, mode, déguisement'),
('33','Société, civilisation et culture, nature morte'),
('34','Société, civilisation et culture, nourriture'),
('35','Société, civilisation et culture, trafic et transport'),
('36','Société, civilisation et culture, vanité'),
('37','Société, civilisation et culture, vie communautaire');

DROP SEQUENCE IF EXISTS bdd_icono_Theme_id_seq;
CREATE SEQUENCE bdd_icono_Theme_id_seq START WITH 37;


DROP TABLE IF EXISTS bdd_icono_Technique CASCADE;
CREATE TABLE bdd_icono_Technique (
id BIGINT PRIMARY KEY NOT NULL,
technique_libelle VARCHAR(255) NOT NULL
);

INSERT INTO bdd_icono_Technique (id,technique_libelle) VALUES 
('1','bois'),
('2','bois transposé sur toile'),
('3','bas-relief'),
('4','crayon noir'),
('5','crayons noir et blanc sur papier gris'),
('6','cuivre'),
('7','détrempe sur bandes juxt. de papier marouflé sur toile'),
('8','eau-forte'),
('9','fond d’or'),
('10','fresque'),
('11','fresque transposé sur toile'),
('12','gouache sur bois'),
('13','gravure'),
('14','gravure sur bois'),
('15','gravure sur cuivre'),
('16','huile'),
('17','huile sur bois'),
('18','huile sur cuivre'),
('19','huile sur toile'),
('20','toile'),
('21','toile avec des oreilles sur les côtés'),
('22','laine'),
('23','peinture ovale'),
('24','fresque transportée sur toile'),
('25','plat rond en faïence'),
('26','plume'),
('27','lavis d’encre de Chine'),
('28','lavis de bistre quadrillé à la sanguine'),
('29','sanguine'),
('30','toile');


DROP SEQUENCE IF EXISTS bdd_icono_Technique_id_seq;
CREATE SEQUENCE bdd_icono_Technique_id_seq START WITH 30;


DROP TABLE IF EXISTS bdd_icono_DonneesBiblio CASCADE;
CREATE TABLE bdd_icono_DonneesBiblio (
id BIGINT PRIMARY KEY NOT NULL,
ref_biblio VARCHAR(255) NOT NULL,
edition VARCHAR(255) NULL
);

INSERT INTO bdd_icono_DonneesBiblio (id,ref_biblio,edition) VALUES 
('1','non-renseigné','2007-CLOUZOT-Images_des_Musiciens');


DROP SEQUENCE IF EXISTS bdd_icono_DonneesBiblio_id_seq;
CREATE SEQUENCE bdd_icono_DonneesBiblio_id_seq START WITH 1;


DROP TABLE IF EXISTS bdd_icono_Institution CASCADE;
CREATE TABLE bdd_icono_Institution (
id BIGINT PRIMARY KEY NOT NULL,
institution_nom VARCHAR(255) NOT NULL,
pays VARCHAR(255) NOT NULL,
ville VARCHAR(255) NULL
);

INSERT INTO bdd_icono_Institution (id,institution_nom,pays,ville) VALUES 
('1','BNF','France','Paris'),
('2','BrB','Belgique','Bruxelles'),
('3','British Library','Royaume-Uni','Londres'),
('4','Arsenal','France','Paris'),
('5','Österreische National Bibliothek','Autriche','Vienne'),
('6','Bodleian Library','Royaume-Uni','Oxford'),
('7','Kulturbesitz dépôt Breslau','Allemagne','Berlin'),
('8','Bibliothèque universitaire','Belgique','Liège'),
('9','Bibliothèque municipale','France','Mâcon'),
('10','Bibliothèque municipale','France','Dijon'),
('11','Bibliothèque municipale','France','Autun');

DROP SEQUENCE IF EXISTS bdd_icono_Institution_id_seq;
CREATE SEQUENCE bdd_icono_Institution_id_seq START WITH 12;


DROP TABLE IF EXISTS bdd_icono_MotCle CASCADE;
CREATE TABLE bdd_icono_MotCle (
id BIGINT PRIMARY KEY NOT NULL,
mot_cle_libelle VARCHAR(255) NOT NULL,
mot_cle_type VARCHAR(255) NOT NULL
);

INSERT INTO bdd_icono_MotCle (id,mot_cle_libelle,mot_cle_type) VALUES 
('1','ange chantant','chant'),
('2','chanteur dans un groupe','chant'),
('3','chœur','chant'),
('4','enfant chantant','chant'),
('5','groupe de chanteurs','chant'),
('6','aérophone','instrument de musique'),
('7','aérophone : flûte ou anche','instrument de musique'),
('8','aérophone à embouchure, chromatique, à trous de jeu','instrument de musique'),
('9','aérophone à embouchure, naturel','instrument de musique'),
('10','aichiluth','instrument de musique'),
('11','alto','instrument de musique'),
('12','archet','instrument de musique'),
('13','basse de Flandre ou bumbass','instrument de musique'),
('14','basse de viole','instrument de musique'),
('15','basse violon','instrument de musique'),
('16','basson','instrument de musique'),
('17','buccine','instrument de musique'),
('18','cadre à sonnailles','instrument de musique'),
('19','castagnettes','instrument de musique'),
('20','chalemie','instrument de musique'),
('21','chitarone','instrument de musique'),
('22','cistre','instrument de musique'),
('23','clavicorde','instrument de musique'),
('24','clochette','instrument de musique'),
('25','clochette à manche','instrument de musique'),
('26','colachon','instrument de musique'),
('27','conque marine','instrument de musique'),
('28','contrebasse','instrument de musique'),
('29','contrebasse de viole','instrument de musique'),
('30','cor naturel','instrument de musique'),
('31','cordes frottées','instrument de musique'),
('32','cordophone avec un manche','instrument de musique'),
('33','cordophone frotté avec un manche, sur caisse plate','instrument de musique'),
('34','cordophones fantastiques avec plectre','instrument de musique'),
('35','corne','instrument de musique'),
('36','cornemuse','instrument de musique'),
('37','cornet','instrument de musique'),
('38','cornet à bouquin','instrument de musique'),
('39','cornet de chasse','instrument de musique'),
('40','cornu','instrument de musique'),
('41','cromorne','instrument de musique'),
('42','crotales','instrument de musique'),
('43','cymbales','instrument de musique'),
('44','épinette','instrument de musique'),
('45','flageolet','instrument de musique'),
('46','flûte','instrument de musique'),
('47','flûte à bec','instrument de musique'),
('48','flûte avec une embouchure terminale','instrument de musique'),
('49','flûte de Pan','instrument de musique'),
('50','flûte ou anche','instrument de musique'),
('51','flûte traversière','instrument de musique'),
('52','grelot(s)','instrument de musique'),
('53','guitare','instrument de musique'),
('54','harpe','instrument de musique'),
('55','harpe sur cadre','instrument de musique'),
('56','harpe sur cadre sans mécanisme','instrument de musique'),
('57','hautbois','instrument de musique'),
('58','instrument à vent','instrument de musique'),
('59','instrument à vent fantastiques','instrument de musique'),
('60','instrument fantastique','instrument de musique'),
('61','instrument peu visible','instrument de musique'),
('62','instruments à cordes','instrument de musique'),
('63','instruments à cordes fantastiques','instrument de musique'),
('64','instruments fantastiques à cordes et à vent','instrument de musique'),
('65','intrument à vent hybride','instrument de musique'),
('66','lira da braccio','instrument de musique'),
('67','luth','instrument de musique'),
('68','luth théorbé','instrument de musique'),
('69','lyre','instrument de musique'),
('70','lyre post antique','instrument de musique'),
('71','lyre sur cadre','instrument de musique'),
('72','mandore','instrument de musique'),
('73','musette de cour','instrument de musique'),
('74','orgue','instrument de musique'),
('75','orgue positif','instrument de musique'),
('76','petit violon','instrument de musique'),
('77','petite harpe','instrument de musique'),
('78','pochette','instrument de musique'),
('79','psaltérion','instrument de musique'),
('80','rebec','instrument de musique'),
('81','sacqueboute','instrument de musique'),
('82','salpinx recourbée','instrument de musique'),
('83','sistre','instrument de musique'),
('84','syrinx','instrument de musique'),
('85','tambour à timbre','instrument de musique'),
('86','tambourin','instrument de musique'),
('87','tambourin à grelots','instrument de musique'),
('88','tambourin à sonnailles','instrument de musique'),
('89','tambourin sur cadre','instrument de musique'),
('90','tambourin sur cadre à sonnailes','instrument de musique'),
('91','ténor de viole','instrument de musique'),
('92','théorbe','instrument de musique'),
('93','timbales','instrument de musique'),
('94','traverso','instrument de musique'),
('95','triangle','instrument de musique'),
('96','triangle à anneaux','instrument de musique'),
('97','trompe','instrument de musique'),
('98','trompe de chasse','instrument de musique'),
('99','trompette','instrument de musique'),
('100','trompette à replis','instrument de musique'),
('101','trompette droite','instrument de musique'),
('102','trompette marine','instrument de musique'),
('103','trompettes droites','instrument de musique'),
('104','tympanon','instrument de musique'),
('105','vièle','instrument de musique'),
('106','vièle à archet','instrument de musique'),
('107','vièle à archet sans cordes','instrument de musique'),
('108','vielle à roue','instrument de musique'),
('109','viole','instrument de musique'),
('110','viole à bras','instrument de musique'),
('111','viole de bras','instrument de musique'),
('112','viole de gambe','instrument de musique'),
('113','violon','instrument de musique'),
('114','violon alto','instrument de musique'),
('115','violone','instrument de musique'),
('116','abbé','generique'),
('117','Acis','generique'),
('118','Acis et Galatée','generique'),
('119','action','generique'),
('120','adoration','generique'),
('121','adoration des bergers','generique'),
('122','adoration des mages','generique'),
('123','âges de l’homme','generique'),
('124','alcool','generique'),
('125','Alexandre','generique'),
('126','allaitement','generique'),
('127','allégorie','generique'),
('128','allégorie de l’art','generique'),
('129','allégorie de l’Eglise et de la Religion','generique'),
('130','Allégorie de la cour d’Isabelle d’Este','generique'),
('131','allégorie de la foi','generique'),
('132','allégorie de la justice','generique'),
('133','allégorie de la musique','generique'),
('134','allégorie de la richesse','generique'),
('135','allégorie de la sagesse','generique'),
('136','allégorie de la victoire','generique'),
('137','allégorie des Vertus','generique'),
('138','allégorie du Temps','generique'),
('139','amour','generique'),
('140','Ancien Testament','generique'),
('141','âne','generique'),
('142','ange','generique'),
('143','ange féminin','generique'),
('144','ange musicien','generique'),
('145','ange musicien assis sur des nuages','generique'),
('146','angelot','generique'),
('147','anges','generique'),
('148','animal','generique'),
('149','animal domestique','generique'),
('150','animal fantastique','generique'),
('151','animaux','generique'),
('152','Annonciation','generique'),
('153','Apollon','generique'),
('154','Apollon et Marsyas','generique'),
('155','Apollon et Pan','generique'),
('156','apôtre','generique'),
('157','apparition','generique'),
('158','apparition du Christ à la Vierge','generique'),
('159','arbre','generique'),
('160','archange','generique'),
('161','arche à Jérusalem','generique'),
('162','architecture','generique'),
('163','Argus','generique'),
('164','Arion','generique'),
('165','aristote','generique'),
('166','armoiries','generique'),
('167','armure','generique'),
('168','arrivée','generique'),
('169','art de la scène','generique'),
('170','art libéral','generique'),
('171','artisan au travail','generique'),
('172','Ascension du Christ (le chœur des anges chantant entoure le Christ)','generique'),
('173','assemblée en plein air','generique'),
('174','attr. Maître de Flore','generique'),
('175','Auguste','generique'),
('176','autel','generique'),
('177','aveugle','generique'),
('178','bacchanale','generique'),
('179','Bacchantes','generique'),
('180','Bacchus','generique'),
('181','bagarre de rue','generique'),
('182','bal','generique'),
('183','Baldassare Perruzzi','generique'),
('184','banquet','generique'),
('185','banquet en plein air','generique'),
('186','barbe','generique'),
('187','barque','generique'),
('188','basilique de Saint-Denis','generique'),
('189','bataille de San Romano','generique'),
('190','bateau','generique'),
('191','berger','generique'),
('192','Bidassoa','generique'),
('193','blond','generique'),
('194','bœuf','generique'),
('195','boire','generique'),
('196','boisson','generique'),
('197','bonnet','generique'),
('198','borgne','generique'),
('199','bouffon','generique'),
('200','cabaret','generique'),
('201','cadeau','generique'),
('202','caducée','generique'),
('203','cahiers de musique','generique'),
('204','campagne','generique'),
('205','caravagisme','generique'),
('206','cardinal','generique'),
('207','Catherine de Medicis','generique'),
('208','cavalier','generique'),
('209','ceinture','generique'),
('210','centaure','generique'),
('211','chalemie','generique'),
('212','champêtre','generique'),
('213','chant','generique'),
('214','chanteuse','generique'),
('215','chapeau','generique'),
('216','chapeau à plume','generique'),
('217','chapelle','generique'),
('218','char','generique'),
('219','char triomphal','generique'),
('220','charette à bras','generique'),
('221','chasse (cynégétique)','generique'),
('222','chasseur','generique'),
('223','chasteté','generique'),
('224','chat','generique'),
('225','chemin','generique'),
('226','cheval','generique'),
('227','cheval ailé','generique'),
('228','cheval marin','generique'),
('229','chevalier','generique'),
('230','chèvre','generique'),
('231','chien','generique'),
('232','chien de chasse','generique'),
('233','Chiron','generique'),
('234','chope','generique'),
('235','Christ','generique'),
('236','Christ enfant','generique'),
('237','clair-obscur','generique'),
('238','Clio','generique'),
('239','cloche','generique'),
('240','clochette','generique'),
('241','cochon','generique'),
('242','codex','generique'),
('243','coiffe','generique'),
('244','collerette','generique'),
('245','collier','generique'),
('246','colombe','generique'),
('247','combat','generique'),
('248','Combat de l’amour et de la chasteté','generique'),
('249','commedia dell’art','generique'),
('250','compétition','generique'),
('251','Compétition musicale d’Apollon','generique'),
('252','composition ornementale','generique'),
('253','Comus','generique'),
('254','concert','generique'),
('255','concert champêtre','generique'),
('256','condottiere','generique'),
('257','contre-plongée','generique'),
('258','contrebasse','generique'),
('259','conversion de Saint Paul','generique'),
('260','corne d’abondance','generique'),
('261','cortège','generique'),
('262','costume','generique'),
('263','coupe','generique'),
('264','couple de danseurs','generique'),
('265','cour','generique'),
('266','couronne','generique'),
('267','couronne de fleurs','generique'),
('268','couronne de laurier','generique'),
('269','couronnement','generique'),
('270','couronnement d’Esther','generique'),
('271','couronnement de la Vierge','generique'),
('272','cours d’eau','generique'),
('273','courtisan','generique'),
('274','crâne','generique'),
('275','crâne symbolisant la vanité','generique'),
('276','crebus','generique'),
('277','crossa d’abbé','generique'),
('278','crosse','generique'),
('279','crucifixion du Christ','generique'),
('280','cyclopes','generique'),
('281','cygne','generique'),
('282','cynégétique','generique'),
('283','dais','generique'),
('284','danse','generique'),
('285','danseur','generique'),
('286','danseuse','generique'),
('287','Daphnis','generique'),
('288','dauphin','generique'),
('289','David','generique'),
('290','David musicien','generique'),
('291','décapitation','generique'),
('292','déesse','generique'),
('293','délit','generique'),
('294','démence','generique'),
('295','Descente de Croix','generique'),
('296','dessus de porte','generique'),
('297','dévotion religieuse','generique'),
('298','diable','generique'),
('299','Diane','generique'),
('300','dieu','generique'),
('301','Dieu (judéo-chrétien)','generique'),
('302','Dionysos','generique'),
('303','diseuse de bonne aventure','generique'),
('304','dit le Parnasse','generique'),
('305','divertissement intérieur','generique'),
('306','divinité de l’eau','generique'),
('307','divinité de la terre','generique'),
('308','divinité du ciel','generique'),
('309','donateur','generique'),
('310','draperie','generique'),
('311','dressoir','generique'),
('312','duc','generique'),
('313','duc de Joyeuse','generique'),
('314','duo','generique'),
('315','eau','generique'),
('316','éclipse','generique'),
('317','Ecole de Fontainebleau','generique'),
('318','écriture','generique'),
('319','église','generique'),
('320','église catholique','generique'),
('321','éléphant','generique'),
('322','empereur','generique'),
('323','enfant','generique'),
('324','enfant de chœur','generique'),
('325','enfant jouant d’un instrument de musique','generique'),
('326','enseignement','generique'),
('327','entrée triomphale','generique'),
('328','épée','generique'),
('329','épinette','generique'),
('330','époque renaissance','generique'),
('331','Erato','generique'),
('332','Eros','generique'),
('333','estampe','generique'),
('334','Esther','generique'),
('335','étagère','generique'),
('336','étendard','generique'),
('337','étendue d’eau','generique'),
('338','étoffe','generique'),
('339','Euterpe','generique'),
('340','évanouissement','generique'),
('341','Eve','generique'),
('342','événement national','generique'),
('343','extase de saint','generique'),
('344','faim','generique'),
('345','faucille','generique'),
('346','faune','generique'),
('347','femme','generique'),
('348','fer à cheval','generique'),
('349','ferme','generique'),
('350','Festin des dieux Apollon','generique'),
('351','festivités','generique'),
('352','fête','generique'),
('353','fête privée','generique'),
('354','fête privée en plein air','generique'),
('355','fête publique','generique'),
('356','fleur','generique'),
('357','fleur de lys','generique'),
('358','flûte','generique'),
('359','flûte de Pan','generique'),
('360','flûtiste','generique'),
('361','folie','generique'),
('362','fond de paysage','generique'),
('363','fontaine','generique'),
('364','forêt','generique'),
('365','Fra Angelico','generique'),
('366','Francesco Baldelli','generique'),
('367','fruit','generique'),
('368','Fugger','generique'),
('369','fuite en Egypte','generique'),
('370','funérailles','generique'),
('371','Gabriel','generique'),
('372','Galatée','generique'),
('373','géant','generique'),
('374','Gédeon','generique'),
('375','gens du voyage','generique'),
('376','glorification de la Vierge','generique'),
('377','Golgotha','generique'),
('378','Goliath','generique'),
('379','gothique international','generique'),
('380','goût','generique'),
('381','Grâces','generique'),
('382','groupe','generique'),
('383','groupe d’instrumentistes','generique'),
('384','groupe de danseurs','generique'),
('385','groupe de famille','generique'),
('386','guerre','generique'),
('387','guitare','generique'),
('388','harnais','generique'),
('389','harpe','generique'),
('390','Haute Renaissance','generique'),
('391','Henri III','generique'),
('392','héraults','generique'),
('393','héraut','generique'),
('394','Hercule','generique'),
('395','Hermès','generique'),
('396','Hérode Antipas','generique'),
('397','histoire d’Enée','generique'),
('398','histoire romaine','generique'),
('399','histoire romaine musicien','generique'),
('400','hommage','generique'),
('401','homme','generique'),
('402','homme ailé tenant sa faux','generique'),
('403','homme nu','generique'),
('404','impératrice','generique'),
('405','insecte','generique'),
('406','instrument à cordes','generique'),
('407','instrument de musique','generique'),
('408','intérieur de demeure','generique'),
('409','Io','generique'),
('410','Isabelle d’Este','generique'),
('411','Italie','generique'),
('412','ivresse','generique'),
('413','ivresse de Bacchus','generique'),
('414','Jan I Brueghel','generique'),
('415','jardin','generique'),
('416','Jean de Sedano','generique'),
('417','Jean du Bois','generique'),
('418','Jephté','generique'),
('419','Jérémie','generique'),
('420','jeune femme','generique'),
('421','jeune fille','generique'),
('422','jeune garçon','generique'),
('423','jeune homme','generique'),
('424','jouer','generique'),
('425','Joyeuse compagnie','generique'),
('426','Jubal','generique'),
('427','juifs','generique'),
('428','Jupiter','generique'),
('429','l’adoration des bergers','generique'),
('430','l’adoration du veau d’or','generique'),
('431','l’Enéide','generique'),
('432','la Jérusalem Délivrée','generique'),
('433','la sibylle de Tibur','generique'),
('434','la Vierge Marie','generique'),
('435','lac','generique'),
('436','lance','generique'),
('437','larrons','generique'),
('438','laurier','generique'),
('439','le Ciel','generique'),
('440','le jugement','generique'),
('441','le jugement de Midas','generique'),
('442','le Paradis céleste','generique'),
('443','le Purgatoire','generique'),
('444','le règne de Comus','generique'),
('445','le supplice de Marsyas','generique'),
('446','le triomphe de Scipion','generique'),
('447','le triomphe de Silène','generique'),
('448','légume','generique'),
('449','les âges de l’homme','generique'),
('450','les cinq sens','generique'),
('451','les funérailles de l’Amour','generique'),
('452','les Muses','generique'),
('453','les Néréides','generique'),
('454','lion','generique'),
('455','littéraire','generique'),
('456','livre','generique'),
('457','livre d’heure','generique'),
('458','livre de musique','generique'),
('459','livre musique','generique'),
('460','Louis XIII le Juste','generique'),
('461','Louise de Lorraine','generique'),
('462','luth','generique'),
('463','lutrin','generique'),
('464','lutte','generique'),
('465','luxure','generique'),
('466','lyre','generique'),
('467','lys','generique'),
('468','madianites','generique'),
('469','Maître de Flore','generique'),
('470','maître de la confrerie du Puy Notre-Dame d’Amiens','generique'),
('471','mammifère','generique'),
('472','manger','generique'),
('473','Maniérisme','generique'),
('474','Mantegna','generique'),
('475','marbre','generique'),
('476','marbrure','generique'),
('477','Margherite de Vaudémont','generique'),
('478','mariage','generique'),
('479','Marie','generique'),
('480','Marie de Médicis','generique'),
('481','Marie de Sedano','generique'),
('482','Mars','generique'),
('483','Mars et Vénus','generique'),
('484','Marsyas','generique'),
('485','masque','generique'),
('486','Matthäus Schwartz','generique'),
('487','médaillon','generique'),
('488','méditation','generique'),
('489','Mellin de Saint Gelais','generique'),
('490','mendiant','generique'),
('491','mer','generique'),
('492','Mercure','generique'),
('493','mère et son enfant','generique'),
('494','messager','generique'),
('495','Minerve','generique'),
('496','Minerve chassant les Vices','generique'),
('497','moine','generique'),
('498','montagne','generique'),
('499','mouton','generique'),
('500','muse','generique'),
('501','Muses','generique'),
('502','musicien','generique'),
('503','musicien-compositeur','generique'),
('504','musique','generique'),
('505','musique de rues','generique'),
('506','musique des rues','generique'),
('507','musique écrite','generique'),
('508','musique populaire','generique'),
('509','musique vocale et instrumentale','generique'),
('510','mythe de la création','generique'),
('511','mythologie','generique'),
('512','mythologie gréco-romaine','generique'),
('513','naïade','generique'),
('514','naissance','generique'),
('515','nappe','generique'),
('516','Nativité du Christ','generique'),
('517','nature morte','generique'),
('518','nature morte aux instruments de musique','generique'),
('519','nature morte d’objets divers','generique'),
('520','nef des fous','generique'),
('521','Neptune','generique'),
('522','noces de Cana','generique'),
('523','Noces de Thétis et Pélée','generique'),
('524','nonne','generique'),
('525','nourriture','generique'),
('526','Nouveau Testament','generique'),
('527','nu','generique'),
('528','nu féminin','generique'),
('529','nu masculin','generique'),
('530','nuage','generique'),
('531','nymphe','generique'),
('532','nymphes de la mer','generique'),
('533','objet religieux','generique'),
('534','obscurité','generique'),
('535','odorat','generique'),
('536','œil','generique'),
('537','oiseau','generique'),
('538','oracle','generique'),
('539','orgue','generique'),
('540','orgue portatif','generique'),
('541','ornement','generique'),
('542','ornement végétal','generique'),
('543','Orphée','generique'),
('544','pain','generique'),
('545','palais','generique'),
('546','Pan','generique'),
('547','paon','generique'),
('548','Paradis','generique'),
('549','parc et forêt','generique'),
('550','partition musicale','generique'),
('551','pastorale et Arcadie','generique'),
('552','pâturage','generique'),
('553','pavement','generique'),
('554','paysage','generique'),
('555','paysage au bord de l’eau','generique'),
('556','paysage avec architecture','generique'),
('557','paysage avec ruines','generique'),
('558','paysage côtier','generique'),
('559','perle','generique'),
('560','personne assise','generique'),
('561','personne debout','generique'),
('562','personnification de la musique','generique'),
('563','Philippe II de Macédoine','generique'),
('564','philosophe','generique'),
('565','Phoebus','generique'),
('566','pipe','generique'),
('567','place','generique'),
('568','plat','generique'),
('569','plates faces de l’orgue positif','generique'),
('570','plumet','generique'),
('571','Pluton','generique'),
('572','poète','generique'),
('573','poisson','generique'),
('574','Polyphème','generique'),
('575','polyptyque','generique'),
('576','pont','generique'),
('577','port','generique'),
('578','portrait','generique'),
('579','portrait à mi-corps','generique'),
('580','portrait d’écrivain','generique'),
('581','portrait d’homme','generique'),
('582','portrait de femme','generique'),
('583','portrait de musicien','generique'),
('584','portrait de personnalité','generique'),
('585','portrait de personne célèbre','generique'),
('586','prairie','generique'),
('587','prédelle','generique'),
('588','Première Renaissance','generique'),
('589','Première Renaissance italienne','generique'),
('590','présentation de Jésus au Temple','generique'),
('591','prière','generique'),
('592','princesse','generique'),
('593','procession','generique'),
('594','procession de noces','generique'),
('595','prophète','generique'),
('596','psaltérion','generique'),
('597','Psyché','generique'),
('598','Pythagore','generique'),
('599','quatre éléments','generique'),
('600','raisin','generique'),
('601','rameur','generique'),
('602','regard expressif','generique'),
('603','règne de Comus','generique'),
('604','reine','generique'),
('605','rempart','generique'),
('606','Renaissance française','generique'),
('607','renommée triomphante','generique'),
('608','repas','generique'),
('609','représentation allégorique d’un pays','generique'),
('610','résurrection du Christ','generique'),
('611','retable','generique'),
('612','réunioin de musiciens','generique'),
('613','réunion','generique'),
('614','réunion dans un cabaret','generique'),
('615','réunion galante','generique'),
('616','richesse','generique'),
('617','rivière','generique'),
('618','robe','generique'),
('619','roi','generique'),
('620','roi de France','generique'),
('621','ruine','generique'),
('622','ruines','generique'),
('623','sacerdoce de la Vierge','generique'),
('624','saint','generique'),
('625','Saint Antoine de Padoue','generique'),
('626','Saint Antoine le Grand','generique'),
('627','Saint Benoît','generique'),
('628','Saint Benoît de Nursis','generique'),
('629','Saint Esprit','generique'),
('630','Saint François d’Assise','generique'),
('631','Saint Jean','generique'),
('632','Saint Jean-Baptiste','generique'),
('633','Saint Jean-Baptiste enfant','generique'),
('634','Saint Jean-Baptiste Salomé','generique'),
('635','Saint Jérôme','generique'),
('636','Saint Joseph','generique'),
('637','Saint Nicolas de Bari','generique'),
('638','Saint Pierre','generique'),
('639','Saint Quentin','generique'),
('640','Saint Sébastien','generique'),
('641','Sainte Anne','generique'),
('642','Sainte Cécile','generique'),
('643','Sainte Dorothée','generique'),
('644','Sainte Lucie','generique'),
('645','Sainte Madeleine','generique'),
('646','Salomon','generique'),
('647','Sappho','generique'),
('648','Saturne (dieu)','generique'),
('649','satyre','generique'),
('650','Schiavone','generique'),
('651','scorpion','generique'),
('652','sculpture','generique'),
('653','se battre','generique'),
('654','seigneur','generique'),
('655','sens ','generique'),
('656','serpent','generique'),
('657','serviteur','generique'),
('658','sibylle','generique'),
('659','société','generique'),
('660','soie','generique'),
('661','soldat','generique'),
('662','soldat et vie du soldat','generique'),
('663','sommeil','generique'),
('664','sourire','generique'),
('665','Squarcione','generique'),
('666','statue de jardin','generique'),
('667','symbole','generique'),
('668','table','generique'),
('669','tambourin','generique'),
('670','Tasse','generique'),
('671','temple','generique'),
('672','tentation','generique'),
('673','tenture','generique'),
('674','Thalie','generique'),
('675','théâtre','generique'),
('676','Thétis','generique'),
('677','toilette','generique'),
('678','tonneau','generique'),
('679','toucher','generique'),
('680','tour de Nesle','generique'),
('681','traîne','generique'),
('682','triangle','generique'),
('683','triomphe','generique'),
('684','triomphe de Galatée','generique'),
('685','triptyque','generique'),
('686','Triton','generique'),
('687','trompe','generique'),
('688','trompette','generique'),
('689','trophée','generique'),
('690','troupeau','generique'),
('691','tsigane','generique'),
('692','univers','generique'),
('693','Uranie','generique'),
('694','vache','generique'),
('695','vaisselle','generique'),
('696','vanité','generique'),
('697','véhicule','generique'),
('698','Venus','generique'),
('699','verre','generique'),
('700','Vertu intellectuelle','generique'),
('701','Vertu morale','generique'),
('702','Vertus','generique'),
('703','vêtement','generique'),
('704','Vices','generique'),
('705','vie de la Vierge','generique'),
('706','vie de Saint Dominique','generique'),
('707','vie politique','generique'),
('708','vièle','generique'),
('709','Vierge','generique'),
('710','Vierge à l’Enfant','generique'),
('711','Vierge à l’Enfant avec saints et ange','generique'),
('712','Vierge à l’Enfant en majesté','generique'),
('713','Vierge à l’Enfant entourés d’anges','generique'),
('714','villa Medicis','generique'),
('715','village','generique'),
('716','villageois','generique'),
('717','vin','generique'),
('718','viole','generique'),
('719','viole d’amour','generique'),
('720','viole de gambe','generique'),
('721','violence','generique'),
('722','violon','generique'),
('723','violoniste','generique'),
('724','vision','generique'),
('725','vol','generique'),
('726','volaille','generique'),
('727','volet ','generique'),
('728','voûte','generique'),
('729','vue','generique'),
('730','vue de ville','generique'),
('731','Vulcain','generique'),
('732','Xerxès Ier','generique'),
('733','Zeus','generique');


DROP SEQUENCE IF EXISTS bdd_icono_MotCle_id_seq;
CREATE SEQUENCE bdd_icono_MotCle_id_seq START WITH 733;


DROP TABLE IF EXISTS bdd_icono_Photographe CASCADE;
CREATE TABLE bdd_icono_Photographe (
id BIGINT PRIMARY KEY NOT NULL,
photographe_nom VARCHAR(255) NULL,
photographe_prenom VARCHAR(255) NULL,
agence VARCHAR(255) NOT NULL
);


DROP SEQUENCE IF EXISTS bdd_icono_Photographe_id_seq;
CREATE SEQUENCE bdd_icono_Photographe_id_seq;


DROP TABLE IF EXISTS bdd_icono_Auteur CASCADE;
CREATE TABLE bdd_icono_Auteur (
id BIGINT PRIMARY KEY NOT NULL,
auteur_nom VARCHAR(255) NOT NULL,
auteur_prenom VARCHAR(255) NULL,
pseudonyme VARCHAR(255) NULL
);


DROP SEQUENCE IF EXISTS bdd_icono_Auteur_id_seq;
CREATE SEQUENCE bdd_icono_Auteur_id_seq;


DROP TABLE IF EXISTS bdd_icono_LieuActivite CASCADE;
CREATE TABLE bdd_icono_LieuActivite (
id BIGINT PRIMARY KEY NOT NULL,
lieu_activite VARCHAR(255) NOT NULL
);


DROP SEQUENCE IF EXISTS bdd_icono_LieuActivite_id_seq;
CREATE SEQUENCE bdd_icono_LieuActivite_id_seq;


DROP TABLE IF EXISTS bdd_icono_Ecole CASCADE;
CREATE TABLE bdd_icono_Ecole (
id BIGINT PRIMARY KEY NOT NULL,
ecole VARCHAR(255) NOT NULL
);


DROP SEQUENCE IF EXISTS bdd_icono_Ecole_id_seq;
CREATE SEQUENCE bdd_icono_Ecole_id_seq;


DROP TABLE IF EXISTS bdd_icono_intImageDonneesBiblio CASCADE;
CREATE TABLE bdd_icono_intImageDonneesBiblio (
id BIGINT PRIMARY KEY NOT NULL,
fk_image_id BIGINT NOT NULL,
fk_donnees_biblio_id BIGINT NOT NULL
);

INSERT INTO bdd_icono_intImageDonneesBiblio (id,fk_image_id,fk_donnees_biblio_id) VALUES
('1','1','1'),
('2','2','1'),
('3','3','1'),
('4','4','1'),
('5','5','1'),
('6','6','1'),
('7','7','1'),
('8','8','1'),
('9','9','1'),
('10','10','1'),
('11','11','1'),
('12','12','1'),
('13','13','1'),
('14','14','1'),
('15','16','1'),
('16','17','1'),
('17','18','1'),
('18','19','1'),
('19','20','1'),
('20','21','1'),
('21','22','1'),
('22','23','1'),
('23','24','1'),
('24','25','1'),
('25','26','1'),
('26','27','1'),
('27','28','1'),
('28','29','1'),
('29','30','1'),
('30','31','1'),
('31','32','1'),
('32','33','1'),
('33','34','1'),
('34','35','1'),
('35','36','1'),
('36','37','1'),
('37','38','1'),
('38','39','1'),
('39','40','1'),
('40','41','1'),
('41','42','1'),
('42','43','1'),
('43','44','1'),
('44','45','1'),
('45','46','1'),
('46','47','1'),
('47','48','1'),
('48','49','1'),
('49','50','1'),
('50','51','1'),
('51','52','1'),
('52','53','1'),
('53','54','1'),
('54','55','1'),
('55','56','1'),
('56','57','1'),
('57','58','1'),
('58','59','1'),
('59','60','1'),
('60','61','1'),
('61','62','1'),
('62','63','1'),
('63','64','1'),
('64','65','1'),
('65','66','1'),
('66','67','1'),
('67','68','1'),
('68','69','1'),
('69','70','1'),
('70','71','1');

DROP SEQUENCE IF EXISTS bdd_icono_intImageDonneesBiblio_id_seq;
CREATE SEQUENCE bdd_icono_intImageDonneesBiblio_id_seq START WITH 70;


DROP TABLE IF EXISTS bdd_icono_intImageMotCle CASCADE;
CREATE TABLE bdd_icono_intImageMotCle (
id BIGINT PRIMARY KEY NOT NULL,
fk_image_id BIGINT NOT NULL,
fk_mot_cle_id BIGINT NOT NULL
);

INSERT INTO bdd_icono_intImageMotCle (id,fk_image_id,fk_mot_cle_id) VALUES 
('1','1','457'),
('2','2','457');

DROP SEQUENCE IF EXISTS bdd_icono_intImageMotCle_id_seq;
CREATE SEQUENCE bdd_icono_intImageMotCle_id_seq START WITH 2;


DROP TABLE IF EXISTS bdd_icono_intImageTheme CASCADE;
CREATE TABLE bdd_icono_intImageTheme (
id BIGINT PRIMARY KEY NOT NULL,
fk_image_id BIGINT NOT NULL,
fk_theme_id BIGINT NOT NULL
);

DROP SEQUENCE IF EXISTS bdd_icono_intImageTheme_id_seq;
CREATE SEQUENCE bdd_icono_intImageTheme_id_seq;


DROP TABLE IF EXISTS bdd_icono_intExtraitDeTechnique CASCADE;
CREATE TABLE bdd_icono_intExtraitDeTechnique (
id BIGINT PRIMARY KEY NOT NULL,
fk_extrait_de_id BIGINT NOT NULL,
fk_technique_id BIGINT NOT NULL
);

DROP SEQUENCE IF EXISTS bdd_icono_intExtraitDeTechnique_id_seq;
CREATE SEQUENCE bdd_icono_intExtraitDeTechnique_id_seq;


DROP TABLE IF EXISTS bdd_icono_intExtraitDeAuteur CASCADE;
CREATE TABLE bdd_icono_intExtraitDeAuteur (
id BIGINT PRIMARY KEY NOT NULL,
fk_extrait_de_id BIGINT NOT NULL,
fk_auteur_id BIGINT NOT NULL
);

DROP SEQUENCE IF EXISTS bdd_icono_intExtraitDeAuteur_id_seq;
CREATE SEQUENCE bdd_icono_intExtraitDeAuteur_id_seq;


DROP TABLE IF EXISTS bdd_icono_intAuteurEcole CASCADE;
CREATE TABLE bdd_icono_intAuteurEcole (
id BIGINT PRIMARY KEY NOT NULL,
fk_auteur_id BIGINT NOT NULL,
fk_ecole_id BIGINT NOT NULL
);

DROP SEQUENCE IF EXISTS bdd_icono_intAuteurEcole_id_seq;
CREATE SEQUENCE bdd_icono_intAuteurEcole_id_seq;


DROP TABLE IF EXISTS bdd_icono_intAuteurLieuActivite CASCADE;
CREATE TABLE bdd_icono_intAuteurLieuActivite (
id BIGINT PRIMARY KEY NOT NULL,
fk_auteur_id BIGINT NOT NULL,
fk_lieu_activite_id BIGINT NOT NULL
);

DROP SEQUENCE IF EXISTS bdd_icono_intAuteurLieuActivite_id_seq;
CREATE SEQUENCE bdd_icono_intAuteurLieuActivite_id_seq;

ALTER TABLE bdd_icono_Image ALTER COLUMN id SET DEFAULT nextval('bdd_icono_Image_id_seq');
ALTER TABLE bdd_icono_DepartementCollection ALTER COLUMN id SET DEFAULT nextval('bdd_icono_DepartementCollection_id_seq');
ALTER TABLE bdd_icono_ExtraitDe ALTER COLUMN id SET DEFAULT nextval('bdd_icono_ExtraitDe_id_seq');
ALTER TABLE bdd_icono_Theme ALTER COLUMN id SET DEFAULT nextval('bdd_icono_Theme_id_seq');
ALTER TABLE bdd_icono_Technique ALTER COLUMN id SET DEFAULT nextval('bdd_icono_Technique_id_seq');
ALTER TABLE bdd_icono_DonneesBiblio ALTER COLUMN id SET DEFAULT nextval('bdd_icono_DonneesBiblio_id_seq');
ALTER TABLE bdd_icono_Institution ALTER COLUMN id SET DEFAULT nextval('bdd_icono_Institution_id_seq');
ALTER TABLE bdd_icono_MotCle ALTER COLUMN id SET DEFAULT nextval('bdd_icono_MotCle_id_seq');
ALTER TABLE bdd_icono_Photographe ALTER COLUMN id SET DEFAULT nextval('bdd_icono_Photographe_id_seq');
ALTER TABLE bdd_icono_Auteur ALTER COLUMN id SET DEFAULT nextval('bdd_icono_Auteur_id_seq');
ALTER TABLE bdd_icono_LieuActivite ALTER COLUMN id SET DEFAULT nextval('bdd_icono_LieuActivite_id_seq');
ALTER TABLE bdd_icono_Ecole ALTER COLUMN id SET DEFAULT nextval('bdd_icono_Ecole_id_seq');
ALTER TABLE bdd_icono_intImageDonneesBiblio ALTER COLUMN id SET DEFAULT nextval('bdd_icono_intImageDonneesBiblio_id_seq');
ALTER TABLE bdd_icono_intImageMotCle ALTER COLUMN id SET DEFAULT nextval('bdd_icono_intImageMotCle_id_seq');
ALTER TABLE bdd_icono_intImageTheme ALTER COLUMN id SET DEFAULT nextval('bdd_icono_intImageTheme_id_seq');
ALTER TABLE bdd_icono_intExtraitDeTechnique ALTER COLUMN id SET DEFAULT nextval('bdd_icono_intExtraitDeTechnique_id_seq');
ALTER TABLE bdd_icono_intExtraitDeAuteur ALTER COLUMN id SET DEFAULT nextval('bdd_icono_intExtraitDeAuteur_id_seq');
ALTER TABLE bdd_icono_intAuteurEcole ALTER COLUMN id SET DEFAULT nextval('bdd_icono_intAuteurEcole_id_seq');
ALTER TABLE bdd_icono_intAuteurLieuActivite ALTER COLUMN id SET DEFAULT nextval('bdd_icono_intAuteurLieuActivite_id_seq');
