# Generated by Django 5.0.3 on 2024-03-20 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_auteur', models.CharField(blank=True, max_length=250, null=True)),
                ('prenom_auteur', models.CharField(blank=True, max_length=250, null=True)),
                ('pseudonyme', models.CharField(blank=True, max_length=250, null=True)),
                ('ecole', models.CharField(blank=True, max_length=250, null=True)),
                ('lieu_activite', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DonneesBiblio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_biblio', models.TextField()),
                ('edition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_institution', models.CharField(blank=True, max_length=250, null=True)),
                ('pays', models.CharField(blank=True, max_length=250, null=True)),
                ('ville', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_motCle', models.CharField(max_length=250)),
                ('type_motCle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_support', models.CharField(blank=True, max_length=250, null=True)),
                ('categorie', models.CharField(blank=True, max_length=250, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_technique', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_theme', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legende', models.TextField(blank=True, null=True)),
                ('num_inventaire', models.CharField(blank=True, max_length=150, null=True)),
                ('dept_colleciton', models.CharField(blank=True, max_length=250, null=True)),
                ('fk_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.institution')),
                ('fk_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.support')),
            ],
        ),
        migrations.CreateModel(
            name='Photographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('num_doc_cesr', models.CharField(blank=True, max_length=50, null=True)),
                ('type_photographie', models.CharField(blank=True, max_length=50, null=True)),
                ('agence', models.CharField(blank=True, max_length=250, null=True)),
                ('credit', models.CharField(blank=True, max_length=250, null=True)),
                ('nom_photographe', models.CharField(blank=True, max_length=250, null=True)),
                ('prenom_photographe', models.CharField(blank=True, max_length=250, null=True)),
                ('couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('lien_telechargement', models.URLField(blank=True, null=True)),
                ('fk_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.image')),
            ],
        ),
        migrations.CreateModel(
            name='IntSupportAuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.auteur')),
                ('fk_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.support')),
            ],
        ),
        migrations.CreateModel(
            name='IntSupportTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.support')),
                ('fk_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.technique')),
            ],
        ),
        migrations.CreateModel(
            name='IntImageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.image')),
                ('fk_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=250)),
                ('prenom_utilisateur', models.CharField(max_length=250)),
                ('fk_autorisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.autorisation')),
            ],
        ),
    ]
