# Generated by Django 5.0.3 on 2024-03-20 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_icono', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntImageDonneesBiblio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_donneesBiblio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.donneesbiblio')),
                ('fk_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.image')),
            ],
        ),
        migrations.CreateModel(
            name='IntImageMotCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.image')),
                ('fk_motCle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.motcle')),
            ],
        ),
    ]
