# Generated by Django 5.0.6 on 2024-06-04 14:26

import bdd_icono.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_icono', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='ecole',
            field=models.CharField(help_text="Indiquez l'école artistique à laquelle appartient l'auteur. Exemple : allemande, française, hollandaise...", max_length=80),
        ),
        migrations.AlterField(
            model_name='extraitde',
            name='date_creation',
            field=models.CharField(blank=True, help_text="Format : AAAA pour une année précise, AAAA - AAAA pour une plage d'années. Préfixes possibles : Avant, Vers, Après", max_length=17, null=True, validators=[bdd_icono.models.validation_date_creation], verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='extraitde',
            name='periode_creation',
            field=models.CharField(blank=True, help_text='Format : Siècle en chiffre, suivi de "e Siècle". Exemple : 3e Siècle, 15e Siècle, 14e Siècle - 15e Siècle. Préfixes possibles : Avant, Vers, Après', max_length=23, null=True, validators=[bdd_icono.models.validation_periode_creation], verbose_name='Période de création'),
        ),
        migrations.AlterField(
            model_name='image',
            name='cote',
            field=models.CharField(blank=True, help_text="Indiquez la cote, en cas d'image provenant d'extrait pouvant être catalogué (manuscrit, livre, lettre, acte officiel etc.)", max_length=150, null=True, verbose_name='Cote'),
        ),
        migrations.AlterField(
            model_name='image',
            name='credit',
            field=models.CharField(blank=True, help_text='Indiquez les crédits relatifs à la photographie.', max_length=250, null=True, verbose_name='Crédit'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(help_text="Indiquez une description de l'image", verbose_name='Description libre'),
        ),
        migrations.AlterField(
            model_name='image',
            name='fk_extrait_de',
            field=models.ForeignKey(blank=True, help_text="Indiquez la provenance de l'image.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdd_icono.extraitde', verbose_name='Extrait'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_format',
            field=models.CharField(editable=False, verbose_name="Format de l'image"),
        ),
        migrations.AlterField(
            model_name='image',
            name='lien_telechargement',
            field=models.ImageField(help_text='Les images doivent être de format TIFF ou JPEG.', upload_to=bdd_icono.models.upload_location, verbose_name='Dépôt du fichier image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='permalien',
            field=models.CharField(blank=True, help_text="Indiquez ici un lien vers le site de l'institution qui fournit la photographie.", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='resolution',
            field=models.CharField(default='non-renseigné', help_text="Indiquez la résolution de l'image en DPI.", max_length=50, verbose_name='Résolution'),
        ),
    ]
