# Generated by Django 5.0.5 on 2024-05-24 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_icono', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraitDe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrait_de_nom', models.CharField(max_length=150)),
                ('categorie', models.CharField(max_length=40, verbose_name='Catégorie')),
                ('date_creation', models.CharField(blank=True, max_length=40, null=True, verbose_name='Date de création')),
                ('periode_creation', models.CharField(blank=True, max_length=40, null=True, verbose_name='Période de création')),
            ],
        ),
        migrations.RemoveField(
            model_name='intsupporttechnique',
            name='fk_support',
        ),
        migrations.RemoveField(
            model_name='intsupporttechnique',
            name='fk_technique',
        ),
        migrations.RemoveField(
            model_name='image',
            name='fk_support',
        ),
        migrations.AlterModelOptions(
            name='donneesbiblio',
            options={'verbose_name': 'Référence bibliographique', 'verbose_name_plural': 'Références bibliographiques'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Thème'},
        ),
        migrations.RenameField(
            model_name='auteur',
            old_name='lieu_activite',
            new_name='lieux_activites',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='donneesBiblio',
            new_name='donnees_biblio',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='motCle',
            new_name='mots_cles',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='theme',
            new_name='themes',
        ),
        migrations.RemoveField(
            model_name='auteur',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='image',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='image',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='image',
            name='n_inventaire',
        ),
        migrations.AddField(
            model_name='auteur',
            name='ecoles',
            field=models.ManyToManyField(related_name='auteurs', through='bdd_icono.IntAuteurEcole', to='bdd_icono.ecole'),
        ),
        migrations.AddField(
            model_name='image',
            name='cote',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cote'),
        ),
        migrations.AddField(
            model_name='image',
            name='mode',
            field=models.CharField(choices=[('Couleur', 'Couleur'), ('N & B', 'Noir et blanc'), ('NR', 'Non-renseigné')], default='Couleur', verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='image',
            name='permalien',
            field=models.ImageField(default='non-renseigné', upload_to='images/', verbose_name='Dépôt du fichier image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auteur',
            name='auteur_nom',
            field=models.CharField(default='non-renseigné', max_length=40, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departementcollection',
            name='fk_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdd_icono.institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='donneesbiblio',
            name='ref_biblio',
            field=models.TextField(default='non-renseigné', verbose_name='Référence bibliographique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(verbose_name='Description libre'),
        ),
        migrations.AlterField(
            model_name='image',
            name='fk_departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.departementcollection', verbose_name='Département de collection'),
        ),
        migrations.AlterField(
            model_name='image',
            name='fk_photographe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.photographe', verbose_name='Photographe'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_format',
            field=models.CharField(choices=[('jpeg', 'JPEG'), ('tiff', 'TIFF'), ('NR', 'Non-renseigné')], default='tiff', verbose_name="Format de l'image"),
        ),
        migrations.AlterField(
            model_name='image',
            name='lien_telechargement',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='image',
            name='n_cesr',
            field=models.CharField(max_length=150, verbose_name='numéro de document CESR'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photographie_type',
            field=models.CharField(choices=[('numerique', 'Numérique'), ('photo', 'Photo'), ('NR', 'Non-renseigné')], default='numerique', verbose_name='Type de photographie'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_nom',
            field=models.CharField(max_length=50, verbose_name="Nom de l'institution"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='pays',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='intauteurecole',
            name='fk_auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.auteur'),
        ),
        migrations.AlterField(
            model_name='intauteurecole',
            name='fk_ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.ecole', verbose_name='Ecole'),
        ),
        migrations.AlterField(
            model_name='intimagedonneesbiblio',
            name='fk_donnees_biblio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.donneesbiblio', verbose_name="Donnée bibliographique correspondante à l'image"),
        ),
        migrations.AlterField(
            model_name='intimagedonneesbiblio',
            name='fk_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.image'),
        ),
        migrations.AlterField(
            model_name='intimagemotcle',
            name='fk_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.image'),
        ),
        migrations.AlterField(
            model_name='intimagemotcle',
            name='fk_mot_cle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.motcle', verbose_name='Mot clé'),
        ),
        migrations.AlterField(
            model_name='intimagetheme',
            name='fk_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.image'),
        ),
        migrations.AlterField(
            model_name='intimagetheme',
            name='fk_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.theme', verbose_name='Thème'),
        ),
        migrations.AlterField(
            model_name='motcle',
            name='mot_cle_libelle',
            field=models.CharField(max_length=20, verbose_name='Libellé du mot clé'),
        ),
        migrations.AlterField(
            model_name='motcle',
            name='mot_cle_type',
            field=models.CharField(max_length=20, verbose_name='Type du mot clé'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='technique_libelle',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_libelle',
            field=models.CharField(max_length=150, verbose_name='Libellé du thème'),
        ),
        migrations.AddField(
            model_name='image',
            name='fk_extrait_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdd_icono.extraitde', verbose_name='ExtraitDe'),
        ),
        migrations.CreateModel(
            name='IntExtraitDeAuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.auteur', verbose_name='Auteur.e')),
                ('fk_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.extraitde')),
            ],
            options={
                'verbose_name': 'Auteur.e du support',
                'verbose_name_plural': 'Auteur.e.s du support',
            },
        ),
        migrations.CreateModel(
            name='IntExtraitDeTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.extraitde')),
                ('fk_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.technique', verbose_name='Technique')),
            ],
            options={
                'verbose_name': 'Technique du support',
                'verbose_name_plural': 'Techniques du support',
            },
        ),
        migrations.DeleteModel(
            name='IntSupportAuteur',
        ),
        migrations.DeleteModel(
            name='IntSupportTechnique',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
        migrations.AddConstraint(
            model_name='intextraitdeauteur',
            constraint=models.UniqueConstraint(fields=('fk_auteur', 'fk_support'), name='unique_support_auteur'),
        ),
        migrations.AddConstraint(
            model_name='intextraitdetechnique',
            constraint=models.UniqueConstraint(fields=('fk_technique', 'fk_support'), name='unique_support_technique'),
        ),
    ]
