# Generated by Django 5.0.5 on 2024-06-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_icono', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='lien_telechargement',
            field=models.ImageField(help_text='Les images doivent être de format TIFF ou JPEG.', upload_to='bdd_icono/hd', verbose_name='Dépôt du fichier image'),
        ),
    ]
