# Generated by Django 5.0.3 on 2024-03-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_icono', '0002_intimagedonneesbiblio_intimagemotcle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographie',
            old_name='format',
            new_name='photographie_format',
        ),
    ]
