# Generated by Django 5.0.5 on 2024-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_icono', '0002_alter_ecole_ecole_alter_extraitde_date_creation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='intimagemotcle',
            constraint=models.UniqueConstraint(fields=('fk_image', 'fk_mot_cle'), name='unique_image_mot_cle'),
        ),
    ]
