# Generated by Django 5.0.3 on 2024-03-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_icono', '0003_rename_format_photographie_photographie_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auteur',
            options={'ordering': ['nom_auteur', 'prenom_auteur'], 'verbose_name': 'Auteur.e', 'verbose_name_plural': 'Auteur.e.s'},
        ),
        migrations.AlterModelOptions(
            name='motcle',
            options={'ordering': ['libelle_motCle']},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['libelle_theme'], 'verbose_name': 'Thème', 'verbose_name_plural': 'Thèmes'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='dept_colleciton',
            new_name='dept_collection',
        ),
        migrations.RemoveField(
            model_name='support',
            name='description',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='folio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='fond_collection',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='photographie',
            name='nom_cliche_physique',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='date_creation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='periode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='intsupporttechnique',
            name='fk_support',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd_icono.support', verbose_name='Support'),
        ),
        migrations.AddConstraint(
            model_name='auteur',
            constraint=models.UniqueConstraint(fields=('nom_auteur', 'prenom_auteur', 'pseudonyme'), name='unique_auteur'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(fields=('nom_institution',), name='unique_nominstitution'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(fields=('libelle_theme',), name='unique_libelletheme'),
        ),
    ]
