# Generated by Django 5.0.5 on 2024-06-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_icono', '0003_intimagemotcle_unique_image_mot_cle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraitde',
            options={'verbose_name': 'Extrait de'},
        ),
        migrations.AddConstraint(
            model_name='departementcollection',
            constraint=models.UniqueConstraint(fields=('departement_nom',), name='unique_departement_nom'),
        ),
        migrations.AddConstraint(
            model_name='extraitde',
            constraint=models.UniqueConstraint(fields=('extrait_de_nom',), name='unique_extrait_de_nom'),
        ),
        migrations.AddConstraint(
            model_name='intauteurecole',
            constraint=models.UniqueConstraint(fields=('fk_auteur', 'fk_ecole'), name='unique_auteur_ecole'),
        ),
        migrations.AddConstraint(
            model_name='intauteurlieuactivite',
            constraint=models.UniqueConstraint(fields=('fk_auteur', 'fk_lieu_activite'), name='unique_auteur_lieu_activite'),
        ),
        migrations.AddConstraint(
            model_name='intimagetheme',
            constraint=models.UniqueConstraint(fields=('fk_image', 'fk_theme'), name='unique_image_theme'),
        ),
    ]
