# Generated by Django 5.0.5 on 2024-06-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd_icono', '0004_alter_extraitde_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraitde',
            name='auteur',
            field=models.ManyToManyField(through='bdd_icono.IntExtraitDeAuteur', to='bdd_icono.auteur'),
        ),
        migrations.AddField(
            model_name='extraitde',
            name='technique',
            field=models.ManyToManyField(through='bdd_icono.IntExtraitDeTechnique', to='bdd_icono.technique'),
        ),
    ]
